# -*- coding: utf-8 -*-
"""Merci.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OQ7DqgbRlgt7xwEbgYe3DtBoF5FpN5Y6
"""

"""
EM Algorithm from scratch: Gaussian Mixture Model
Pooled dataset: father heights (one per family) + children heights (all rows)
Goal: recover two latent groups (no labels used during fitting) via
soft (probabilistic) cluster assignment, and compare against a hard
mean-split baseline.
"""

import numpy as np
import pandas as pd

# ---------------------------------------------------------------
# 1. LOAD + POOL THE DATA (unsupervised: labels only used for sanity check)
# ---------------------------------------------------------------
df = pd.read_csv("GaltonFamilies.csv")

fathers = df.drop_duplicates(subset="family")["father"].values   # one per family
children = df["childHeight"].values                              # all rows

x = np.concatenate([fathers, children])   # THE unlabeled dataset EM sees
n = len(x)

print(f"Pooled dataset size: n = {n}")
print(f"(True) father mean={fathers.mean():.3f}, children mean={children.mean():.3f}")
print(f"Global mean of pooled data: {x.mean():.3f}\n")

# ---------------------------------------------------------------
# 2. GAUSSIAN DENSITY FUNCTION
# ---------------------------------------------------------------
def gaussian_pdf(x, mu, sigma2):
    coeff = 1.0 / np.sqrt(2 * np.pi * sigma2)
    exponent = -((x - mu) ** 2) / (2 * sigma2)
    return coeff * np.exp(exponent)

# ---------------------------------------------------------------
# 3. E-STEP: compute responsibilities gamma_i = P(component 1 | x_i)
# ---------------------------------------------------------------
def e_step(x, mu1, mu2, sigma1_sq, sigma2_sq, pi1, pi2):
    w1 = pi1 * gaussian_pdf(x, mu1, sigma1_sq)
    w2 = pi2 * gaussian_pdf(x, mu2, sigma2_sq)
    total = w1 + w2
    gamma1 = w1 / total     # responsibility for component 1
    gamma2 = w2 / total     # responsibility for component 2 (= 1 - gamma1)
    return gamma1, gamma2

# ---------------------------------------------------------------
# 4. M-STEP: update parameters using the responsibilities as soft weights
# ---------------------------------------------------------------
def m_step(x, gamma1, gamma2):
    N1 = gamma1.sum()
    N2 = gamma2.sum()

    mu1 = np.sum(gamma1 * x) / N1
    mu2 = np.sum(gamma2 * x) / N2

    sigma1_sq = np.sum(gamma1 * (x - mu1) ** 2) / N1
    sigma2_sq = np.sum(gamma2 * (x - mu2) ** 2) / N2

    pi1 = N1 / len(x)
    pi2 = N2 / len(x)

    return mu1, mu2, sigma1_sq, sigma2_sq, pi1, pi2

# ---------------------------------------------------------------
# 5. LOG-LIKELIHOOD: measures how well current params explain the data.
#    Should increase (or stay flat) every iteration -- this is EM's guarantee.
# ---------------------------------------------------------------
def log_likelihood(x, mu1, mu2, sigma1_sq, sigma2_sq, pi1, pi2):
    mixture_density = (pi1 * gaussian_pdf(x, mu1, sigma1_sq) +
                        pi2 * gaussian_pdf(x, mu2, sigma2_sq))
    return np.sum(np.log(mixture_density))

# ---------------------------------------------------------------
# 6. INITIALIZATION (iteration 0) -- fully unsupervised.
#    We sort the pooled data and split it into a lower/upper half by
#    QUANTITY of points (not by true label) to get a reasonable starting
#    guess. This does not use the father/children labels at all.
# ---------------------------------------------------------------
x_sorted = np.sort(x)
median_idx = n // 2
lower_half = x_sorted[:median_idx]
upper_half = x_sorted[median_idx:]

mu1, mu2 = lower_half.mean(), upper_half.mean()
sigma1_sq = x.var()   # start both components at the overall variance
sigma2_sq = x.var()
pi1, pi2 = 0.5, 0.5

# ---------------------------------------------------------------
# 7. RUN EM AND BUILD THE TRACKING TABLE
# ---------------------------------------------------------------
table_rows = []

ll0 = log_likelihood(x, mu1, mu2, sigma1_sq, sigma2_sq, pi1, pi2)
table_rows.append((0, mu1, mu2, sigma1_sq, sigma2_sq, pi1, pi2, ll0))

n_iterations = 2
for it in range(1, n_iterations + 1):
    gamma1, gamma2 = e_step(x, mu1, mu2, sigma1_sq, sigma2_sq, pi1, pi2)
    mu1, mu2, sigma1_sq, sigma2_sq, pi1, pi2 = m_step(x, gamma1, gamma2)
    ll = log_likelihood(x, mu1, mu2, sigma1_sq, sigma2_sq, pi1, pi2)
    table_rows.append((it, mu1, mu2, sigma1_sq, sigma2_sq, pi1, pi2, ll))

print(f"{'Iter':<5}{'mu1':<10}{'mu2':<10}{'sigma1^2':<12}{'sigma2^2':<12}{'pi1':<8}{'pi2':<8}{'Log-Lik':<12}")
for row in table_rows:
    it, m1, m2, s1, s2, p1, p2, ll = row
    print(f"{it:<5}{m1:<10.4f}{m2:<10.4f}{s1:<12.4f}{s2:<12.4f}{p1:<8.4f}{p2:<8.4f}{ll:<12.4f}")

# ---------------------------------------------------------------
# 8. CLASSIFY A NEW TEST HEIGHT (posterior probabilities)
#    Whichever component ends up with the LOWER mean = "Children",
#    the higher mean = "Pros" (per the assignment's labeling convention).
# ---------------------------------------------------------------
def classify_height(test_height, mu1, mu2, sigma1_sq, sigma2_sq, pi1, pi2):
    g1, g2 = e_step(np.array([test_height]), mu1, mu2, sigma1_sq, sigma2_sq, pi1, pi2)
    # map component 1 / 2 to Children / Pros by comparing means
    if mu1 < mu2:
        p_child, p_pro = g1[0], g2[0]
    else:
        p_child, p_pro = g2[0], g1[0]
    return p_child, p_pro

test_height = 71.0
p_child, p_pro = classify_height(test_height, mu1, mu2, sigma1_sq, sigma2_sq, pi1, pi2)
print(f"\nTest height = {test_height} in")
print(f"P(Child) = {p_child:.4f}")
print(f"P(Pro)   = {p_pro:.4f}")

# ---------------------------------------------------------------
# 9. THE MEAN-SPLIT BASELINE (for comparison in your verbal answer)
# ---------------------------------------------------------------
global_mean = x.mean()
pile_low = x[x <= global_mean]
pile_high = x[x > global_mean]
print(f"\n--- Naive mean-split baseline ---")
print(f"Global mean cutoff: {global_mean:.3f}")
print(f"Pile 1 (<= mean): n={len(pile_low)}, mean={pile_low.mean():.3f}")
print(f"Pile 2 (>  mean): n={len(pile_high)}, mean={pile_high.mean():.3f}")

overlap = x[(x > mu1 - 3) & (x < mu1 + 3)] if mu1 < mu2 else x[(x > mu2 - 3) & (x < mu2 + 3)]
print(f"Points within +/-3in of the lower (children) component mean: {len(overlap)} / {n} ({100*len(overlap)/n:.1f}%)")
